theme: jekyll-theme-minimal
title: The Recipe for Mango Wasiwas
description: This recipe was made in loving memory of Lola Lisa (1933-2021)
logo: https://cdn.iconscout.com/icon/free/png-256/mango-fruit-vitamin-healthy-summer-food-31184.png
