theme: jekyll-theme-minimal
title: The Recipe for Mango Wasiwas
description: This recipe was made in loving memory of my grandmother/Lola Lisa (1933-2021)
logo: https://i.postimg.cc/k4sRHZ0k/mangowasiwas.jpg
